Feature/1 kundkontolista
PROG17/BankAppALMCharbel pull request #1
Opened 2018-11-25 19:57 UTC by Charbely

Har tagit mycket från ditt projekt i och med att jag har lärt mig en hel del, det hjälpte mig att lära mig bättre nu när jag jobbade med mitt egna.

**Verifiera**
- Lista med kunder och deras konton ska synas på startsidan.
- Kundens kundnummer, namn och dess konton ska synas i listan.
- Kontonummer och saldo på respektive konto ska synas i listan.

2018-11-25 21:01 UTC, applejag requested changes
Nice work. Projektet körs inte utan error, se kommentarer på BankDataRepository.cs

Annars fint jobbat! Dem tre punkterna att verifiera går igenom.

2018-11-25 21:01 UTC, applejag commented on BankRepo/BankDataRepository.cs
> +            var file = new StreamReader("C:\\Users\\charb\\source\\repos\\BankAppALMCharbel\\BankRepo\\bankdata.txt");
Din `file` variabel blir inte Disposed direkt. Rekommenderat att göra din reading inuti en `using` sats.  
Alltså:
```cs
using (var file = new StreamReader("...")) {
    // din kod för att läsa filen
}
```

2018-11-25 21:01 UTC, applejag commented on BankRepo/BankDataRepository.cs
> +            var file = new StreamReader("C:\\Users\\charb\\source\\repos\\BankAppALMCharbel\\BankRepo\\bankdata.txt");
Path i din StreamReader är ju en s.k. _absolute path_. Akta dig från sådana i projekt. Är inte portabelt då min user inte heter _charb_ på min dator. 

En lösning är att lägga till inställningen _**Copy to Output Directory**_ på `bankdata.txt` och sedan använda en relativ sökväg. Problem uppstår då dock eftersom filen hamnar i din bin/ mapp och `Directory.GetCurrentDirectory()` pekar på projektets mapp i ASP.NET applikationer, så du måste peka om den till den sökväg dit projektet byggs (t.ex bin/Debug, bin/Release). _(det är denna metodik jag gick för i mitt projekt)_

En alternativ lösning att rekommenderas är att lägga till bankdata.txt som en _**Embedded resource**_ (i inställningen för _**Build Action**_ på `bankdata.txt` filen). Sedan läsa av filen som en embedded resource istället.  
Exempel:
```cs
using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("BankRepo.bankdata.txt"))
using (var file = new StreamReader(stream)) {
    // din kod för att läsa filen
}
```

2018-11-25 22:33 UTC, Charbely commented on BankRepo/BankDataRepository.cs
> +            var file = new StreamReader("C:\\Users\\charb\\source\\repos\\BankAppALMCharbel\\BankRepo\\bankdata.txt");
Fixat

2018-11-25 22:33 UTC, Charbely commented on BankRepo/BankDataRepository.cs
> +            var file = new StreamReader("C:\\Users\\charb\\source\\repos\\BankAppALMCharbel\\BankRepo\\bankdata.txt");
Fixat

2018-11-25 23:02 UTC, Charbely reviewed
Fixade problemet med sökvägen och la till using(...){"code"}

2018-11-26 10:38 UTC, applejag approved these changes
Awesome pawsome!

2018-11-28 19:13 UTC, merged